### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by devilxsam** [r0ld3x/terabox-downloader-bot#3]
Traceback (most recent call last):
  File "/home/epiksam14/terabox-downloader-bot/main.py", line 9, in <module>
    from terabox import get_data, init_download
  File "/home/epiksam14/terabox-downloader-bot/terabox.py", line 6, in <module>
    from tools import extract_surl_from_url, get_formatted_size
  File "/home/epiksam14/terabox-downloader-bot/tools.py", line 301, in <module>
    async def is_user_on_chat(bot: Client, chat_id: int, user_id: int) -> ChatMember | bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by r0ld3x** [comment]
Your python version

**Comment by r0ld3x** [comment]
Your python version

**Comment by devilxsam** [comment]
3.9.2

**Comment by r0ld3x** [comment]
> 3.9.2

try 3.12
