### ISSUE TITLE
How to solve this error

### ISSUE THREAD

**Issue by dikshitd5** [r0ld3x/terabox-downloader-bot#6]
During handling of the above exception, another exception occurred:
2024-02-17T07:42:18.151319+00:00 app[worker.1]: 
2024-02-17T07:42:18.151319+00:00 app[worker.1]: Traceback (most recent call last):
2024-02-17T07:42:18.151319+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/client/updates.py", line 561, in _dispatch_update
2024-02-17T07:42:18.151320+00:00 app[worker.1]:     await builder.resolve(self)
2024-02-17T07:42:18.151320+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/events/common.py", line 99, in resolve
2024-02-17T07:42:18.151320+00:00 app[worker.1]:     await self._resolve(client)
2024-02-17T07:42:18.151320+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/events/newmessage.py", line 94, in _resolve
2024-02-17T07:42:18.151320+00:00 app[worker.1]:     self.from_users = await _into_id_set(client, self.from_users)
2024-02-17T07:42:18.151321+00:00 app[worker.1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-17T07:42:18.151321+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/events/common.py", line 33, in _into_id_set
2024-02-17T07:42:18.151321+00:00 app[worker.1]:     chat = await client.get_input_entity(chat)
2024-02-17T07:42:18.151321+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-17T07:42:18.151322+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/client/users.py", line 439, in get_input_entity
2024-02-17T07:42:18.151322+00:00 app[worker.1]:     await self._get_entity_from_string(peer))
2024-02-17T07:42:18.151322+00:00 app[worker.1]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-17T07:42:18.151322+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/telethon/client/users.py", line 536, in _get_entity_from_string
2024-02-17T07:42:18.151323+00:00 app[worker.1]:     raise ValueError('Cannot get entity by phone number as a '
2024-02-17T07:42:18.151324+00:00 app[worker.1]: ValueError: Cannot get entity by phone number as a bot (try using integer IDs, not strings)

**Comment by r0ld3x** [comment]
fill config.py properly
